apiVersion: v1

kind: Pod                                            

metadata:
  name: devops                                       
  labels:
    env: prod

spec:
  containers:
    - name: devops
      image: nginx 
